use_frameworks!

platform :ios, '8.0'

target 'PodLibTest_Example' do
  pod 'PodLibTest', :path => '../'

  target 'PodLibTest_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
